// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lcrzjntafttrvcotybej.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxjcnpqbnRhZnR0cnZjb3R5YmVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4MzEzNzksImV4cCI6MjA1ODQwNzM3OX0.vMraiiP2PDfw_8Gm2wQnWpxlh_2NKr6eZCyFJp79GRQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);